Attribute VB_Name = "modvariable"
'Program Name   : Ant Inventory System
'Alias          : Ant Inventory
'Copyright      : 2012 - 2014
'Company        : Antsoft Media
'Programmer     : U. Selamat Raharja & Chandra Kirana
'ver            : 2.14
'Update 2020    : 04/08 : Add frmoutrankasedit (gl_ledger)
'               : 06/08 : Update frmeditsop,frmaddsop,frmaddlot (prod_sop) edit lot wip base
'               : 12/08 : Update Report bukti_pengeluaran.rpt
'               : 24/08 : Add proc(am_telegram_omsetsales)
'               : 10/11 : Update Tgl scan (prod_sop.dll)
'Update 2022    : 06/06 : Update nilaikurs untuk active report(frmlaporancbo)

'Jika error File no longer support hapus file oca di Program Files (x86)\Microsoft Visual Studio\VB98\
'dan hapus file CODEJO~1/2/3.oca di Program Files (x86)\MINDSYS\bin\

Option Explicit

'Declared Information Aplication
Global Const FullAppName = "Ant Inventory System"
Global Const AppName = "Ant Inventory System"
Global Const AppVer = "Ver. 2.14"
Global Const AppComp = "Antsoft Media"
Global Const AppCopyright = " 2012-2013"
Global Const AppProgrammer1 = "Selamat Raharja"
Global Const AppProgrammer2 = "Chandra Kirana"
Global Const Bahasa = "IND"

Global AppPath As String
Global UserOnline As String
Global UserOnLineLevel As String
Global UserOnlineDept As String
Global TglServer As String

'Declare Database Property
Global dbServer As String
Global DBName As String
Global dbPort As String
Global dbUser As String
Global dbPass As String
Global dsn As String
Global remoteserver As Boolean
Global dbRemoteServer As String

Public namatabel As String
Public carisql1 As String
Public hasil, hasil1, hasil2, hasil3 As String
Public format_coa As String
Public kuser, kcomp, nmuser As String
Global Const msgimg1 = "field.html"

Public ctrloption As CommandBarPopup
Public controlabout As CommandBarButton
Public control As CommandBarControl

Global Const ID_INDICATOR_CAPS As Long = 59137
Global Const ID_INDICATOR_NUM = 59138
Global Const ID_INDICATOR_SCRL = 59139
'Declared Status Bars
Global Const ID_INDICATOR_USR = 59140
Global Const ID_INDICATOR_SERVER = 59141
Global Const ID_INDICATOR_DTP1 = 59142
Global Const ID_INDICATOR_DTP2 = 59143
Global Const ID_INDICATOR_CHK = 59144
Global Const ID_INDICATOR_DARITGL = 59145
Global Const ID_INDICATOR_SDTGL = 59146
Global Const ID_INDICATOR_FASTSEARCH = 59147

'ID FILE
Global Const ID_FILE = 10
Global Const ID_FILE_CHANGEPASS = 11
Global Const ID_FILE_LOGOUT = 12
Global Const ID_FILE_EXIT = 13
Global Const ID_FILE_VIEWSTOKBAHANBAKU = 14
Global Const ID_FILE_VIEWSTOKBARANGJADI = 15
Global Const ID_FILE_PESANSYSTEM = 16
Global Const ID_FILE_DASHBOARD = 17

Public FILE_VIEWSTOKBAHANBAKU As CommandBarButton
Public FILE_VIEWSTOKBARANGJADI As CommandBarButton
Public FILE_PESANSYSTEM As CommandBarButton
Public FILE_EXIT As CommandBarButton

'################################## MASTER ID ##########################
Global Const ID_MASTER = 100
Global Const ID_MASTER_DATABASE = 1001
Global Const ID_MASTER_DATABASE_KONEKSI = 10011
Global Const ID_MASTER_DATABASE_KONEKSISQL = 100111
Global Const ID_MASTER_DATABASE_KONEKSI_BACKUP = 100112
Global Const ID_MASTER_DATABASE_KONEKSI_RESTORE = 100113
Global Const ID_MASTER_DATABASE_MAINTENANCE = 10012
Global Const ID_MASTER_DATABASE_MAINTENANCE_IMPORTBAHANBAKU = 100121
Global Const ID_MASTER_DATABASE_MAINTENANCE_IMPORTBARANGJADI = 100122
Global Const ID_MASTER_DATABASE_MAINTENANCE_BROADCASTMESSAGE = 100123


Global Const ID_MASTER_MANAGEUSER = 1002
Global Const ID_MASTER_MANAGEUSER_USER = 10021
Global Const ID_MASTER_MANAGEUSER_DEPARTEMEN = 10022
Global Const ID_MASTER_MANAGEUSER_MODUL = 10023
Global Const ID_MASTER_MANAGEUSER_LEVEL = 10024
Global Const ID_MASTER_MANAGEUSER_USERDEPT = 10025

Global Const ID_MASTER_TELEGRAM = 1003
Global Const ID_MASTER_TELEGRAM_BOT = 10031

'#################################### HRD ID #########################
Global Const ID_PERSONALIA = 200

'################################### PEMBELIAN ID ####################
Global Const ID_PEMBELIAN = 300
Global Const ID_PEMBELIAN_MAINMENU = 301
Global Const ID_PEMBELIAN_TABEL = 3011

Global Const ID_PEMBELIAN_TABEL_SUPPLIER = 30111
Global Const ID_PEMBELIAN_TABEL_SUPPLIER_ADD = 301111
Global Const ID_PEMBELIAN_TABEL_SUPPLIER_CHANGE = 301112
Global Const ID_PEMBELIAN_TABEL_SUPPLIER_IMPORTEXPORT = 301113
Global Const ID_PEMBELIAN_TABEL_SUPPLIER_LIST = 301114
Global Const ID_PEMBELIAN_TABEL_SUPPLIER_PRICELIST = 301115
Global Const ID_PEMBELIAN_TABEL_SUPPLIER_GRAPRICE = 301116

Global Const ID_PEMBELIAN_TABEL_SATUAN = 30112
Global Const ID_PEMBELIAN_TABEL_SATUAN_ADD = 301121
Global Const ID_PEMBELIAN_TABEL_SATUAN_CHANGE = 301122
Global Const ID_PEMBELIAN_TABEL_SATUAN_IMPORTEXPORT = 301123
Global Const ID_PEMBELIAN_TABEL_SATUAN_LIST = 301124

Global Const ID_PEMBELIAN_TABEL_BAHANBAKU = 30113
Global Const ID_PEMBELIAN_TABEL_BAHANBAKU_MANAGE = 301131
Global Const ID_PEMBELIAN_TABEL_BAHANBAKU_IMPORTEXPORT = 301132
Global Const ID_PEMBELIAN_TABEL_BAHANBAKU_LIST = 301133

Global Const ID_PEMBELIAN_TABEL_CUR = 30114
Global Const ID_PEMBELIAN_TABEL_CUR_ADD = 301141
Global Const ID_PEMBELIAN_TABEL_CUR_CHANGE = 301142
Global Const ID_PEMBELIAN_TABEL_CUR_IMPORTEXPORT = 301143
Global Const ID_PEMBELIAN_TABEL_CUR_LIST = 301144

'Global Const ID_PEMBELIAN_TABEL_BANK = 30115
'Global Const ID_PEMBELIAN_TABEL_BANK_ADD = 301151
'Global Const ID_PEMBELIAN_TABEL_BANK_CHANGE = 301152
'Global Const ID_PEMBELIAN_TABEL_BANK_IMPORTEXPORT = 301153
'Global Const ID_PEMBELIAN_TABEL_BANK_LIST = 301154

Global Const ID_PEMBELIAN_TABEL_PACKAGING = 30116
Global Const ID_PEMBELIAN_TABEL_PACKAGING_ADD = 301161
Global Const ID_PEMBELIAN_TABEL_PACKAGING_CHANGE = 301162

Global Const ID_PEMBELIAN_TABEL_MINSTOCK = 30117
Global Const ID_PEMBELIAN_TABEL_MINSTOCK_ADD = 301171
Global Const ID_PEMBELIAN_TABEL_MINSTOCK_CHANGE = 301172
Global Const ID_PEMBELIAN_TABEL_MINSTOCK_LIST = 301173

Global Const ID_PEMBELIAN_MUTASIBARANG = 3012
Global Const ID_PEMBELIAN_MUTASIBARANG_ADD = 30121
Global Const ID_PEMBELIAN_MUTASIBARANG_CHANGE = 30122
Global Const ID_PEMBELIAN_MUTASIBARANG_IMPORTEXPORT = 30123
Global Const ID_PEMBELIAN_MUTASIBARANG_LIST = 30124
Global Const ID_PEMBELIAN_MUTASIBARANG_BASE = 30125

Global Const ID_PEMBELIAN_PURCHASING = 3013
Global Const ID_PEMBELIAN_PURCHASING_PO = 30131
Global Const ID_PEMBELIAN_PURCHASING_PO_ADD = 301311
Global Const ID_PEMBELIAN_PURCHASING_PO_CHANGE = 301312
Global Const ID_PEMBELIAN_PURCHASING_PO_IMPORTEXPORT = 301313
Global Const ID_PEMBELIAN_PURCHASING_PO_CLOSECANCEL = 301314

Global Const ID_PEMBELIAN_PURCHASING_PENERIMAANBARANG = 30132
Global Const ID_PEMBELIAN_PURCHASING_PENERIMAANBARANG_ADD = 301321
Global Const ID_PEMBELIAN_PURCHASING_PENERIMAANBARANG_CHANGE = 301322
Global Const ID_PEMBELIAN_PURCHASING_PENERIMAANBARANG_IMPORTEXPORT = 301323
Global Const ID_PEMBELIAN_PURCHASING_PENERIMAANBARANG_RETUR = 301324
Global Const ID_PEMBELIAN_PURCHASING_PENERIMAANBARANG_PRINTBPB = 301325

Global Const ID_PEMBELIAN_PURCHASING_PEMAKAIANBAHANBAKU = 30133
Global Const ID_PEMBELIAN_PURCHASING_PEMAKAIANBAHANBAKU_ADD = 301331
Global Const ID_PEMBELIAN_PURCHASING_PEMAKAIANBAHANBAKU_CHANGE = 301332
Global Const ID_PEMBELIAN_PURCHASING_PEMAKAIANBAHANBAKU_IMPORTEXPORT = 301333
Global Const ID_PEMBELIAN_PURCHASING_PEMAKAIANBAHANBAKU_SISA = 301334

Global Const ID_PEMBELIAN_PURCHASING_CONFIRM = 30134
Global Const ID_PEMBELIAN_PURCHASING_CONFIRM_CONFIRMPENERIMAANBARANG = 301341
Global Const ID_PEMBELIAN_PURCHASING_CONFIRM_CONFIRMPENERIMAANBARANG_ADD = 3013411
Global Const ID_PEMBELIAN_PURCHASING_CONFIRM_CONFIRMPENERIMAANBARANG_REPRINT = 3013412
Global Const ID_PEMBELIAN_PURCHASING_CONFIRM_CONFIRMRETURPENERIMAANBARANG = 301342
Global Const ID_PEMBELIAN_PURCHASING_CONFIRM_UNCONFIRMPENERIMAANBARANG = 301343
Global Const ID_PEMBELIAN_PURCHASING_CONFIRM_UNCOFIRMRETURPENERIMAANBARANG = 301344
Global Const ID_PEMBELIAN_PURCHASING_CONFIRM_CREATEVOUCHER = 301345

Global Const ID_PEMBELIAN_PURCHASING_INQUIRY = 30135
Global Const ID_PEMBELIAN_PURCHASING_PRINTPO = 30136
Global Const ID_PEMBELIAN_PURCHASING_LAPPO = 30137
Global Const ID_PEMBELIAN_PURCHASING_LAPPEMBELIAN = 30138
Global Const ID_PEMBELIAN_PURCHASING_LAPCONPEMBELIAN = 30139
Global Const ID_PEMBELIAN_PURCHASING_LAPPEMAKAIANBB = 30140
Global Const ID_PEMBELIAN_PURCHASING_LAPVOUCER = 30141
Global Const ID_PEMBELIAN_PURCHASING_LAPPROSESVOUCHER = 30142

Global Const ID_PEMBELIAN_PURCHASING_PERMINTAAN = 30143
Global Const ID_PEMBELIAN_PURCHASING_PERMINTAAN_ADD = 301431
Global Const ID_PEMBELIAN_PURCHASING_PERMINTAAN_CHANGE = 301432
Global Const ID_PEMBELIAN_PURCHASING_PERMINTAAN_CLOSE = 301433
Global Const ID_PEMBELIAN_PURCHASING_PERMINTAAN_LIST = 301434
Global Const ID_PEMBELIAN_PURCHASING_PERMINTAAN_PRINT = 301435
Global Const ID_PEMBELIAN_PURCHASING_PERMINTAAN_DAYSCOUNT = 301436

Global Const ID_PEMBELIAN_HUTANG = 3014
Global Const ID_PEMBELIAN_HUTANG_PBYHUTANG = 30141
Global Const ID_PEMBELIAN_HUTANG_PBYHUTANG_ADD = 301411
Global Const ID_PEMBELIAN_HUTANG_PBYHUTANG_CHANGE = 301412
Global Const ID_PEMBELIAN_HUTANG_PBYHUTANG_UNPOST = 301413
Global Const ID_PEMBELIAN_HUTANG_KOREKSIHTN = 30142
Global Const ID_PEMBELIAN_HUTANG_KOREKSIHTN_ADD = 301421
Global Const ID_PEMBELIAN_HUTANG_KOREKSIHTN_CHANGE = 301422
Global Const ID_PEMBELIAN_HUTANG_LISTKOREKSI = 30143
Global Const ID_PEMBELIAN_HUTANG_LISTPBYHUTANG = 30144
Global Const ID_PEMBELIAN_HUTANG_LAPSISAHUTANG = 30145
Global Const ID_PEMBELIAN_HUTANG_LAPBYJT = 30146

Global Const ID_PEMBELIAN_GIRO = 3015
Global Const ID_PEMBELIAN_UTILITY = 3016
Global Const ID_PEMBELIAN_UTILITY_FASTSEARCH = 30161
Global Const ID_PEMBELIAN_UTILITY_ADJUSTSTOK = 30162
Global Const ID_PEMBELIAN_UTILITY_EXPORTDATAPABRIK = 30163
Global Const ID_PEMBELIAN_UTILITY_IMPORTDATA = 30164
Global Const ID_PEMBELIAN_UTILITY_OPTIONS = 30165

'###################################### PRODUKSI ID ###########################
Global Const ID_PRODUKSI = 500
Global Const ID_PRODUKSI_MAINMENU = 5001
Global Const ID_PRODUKSI_MAINMENU_TABLES = 50011
'Global Const ID_PRODUKSI_MAINMENU_TABLES_REAKTOR = 500111
'Global Const ID_PRODUKSI_MAINMENU_TABLES_REAKTOR_ADD = 5001112
'Global Const ID_PRODUKSI_MAINMENU_TABLES_REAKTOR_CHANGE = 5001113
Global Const ID_PRODUKSI_MAINMENU_TABLES_RESEP = 500112
Global Const ID_PRODUKSI_MAINMENU_TABLES_RESEP_LEM = 5001121
Global Const ID_PRODUKSI_MAINMENU_TABLES_RESEP_KARET = 5001122
Global Const ID_PRODUKSI_MAINMENU_TABLES_RESEP_LISTLEM = 5001123
Global Const ID_PRODUKSI_MAINMENU_TABLES_KONVERSI = 500113
Global Const ID_PRODUKSI_MAINMENU_TABLES_KONVERSI_ADD = 5001132
Global Const ID_PRODUKSI_MAINMENU_TABLES_KONVERSI_CHANGE = 5001133
Global Const ID_PRODUKSI_MAINMENU_TABLES_KONVERSI_LIST = 5001134
Global Const ID_PRODUKSI_MAINMENU_TABLES_KONVERSI_UNIT = 5001135
Global Const ID_PRODUKSI_MAINMENU_TABLES_DEFINEKG = 500114

Global Const ID_PRODUKSI_MAINMENU_TABLES_RNCPROD = 500115
Global Const ID_PRODUKSI_MAINMENU_TABLES_RNCPROD_ADD = 5001151
Global Const ID_PRODUKSI_MAINMENU_TABLES_RNCPROD_CHANGE = 5001152
Global Const ID_PRODUKSI_MAINMENU_TABLES_RNCPROD_LIST = 5001153
Global Const ID_PRODUKSI_MAINMENU_TABLES_KATEGORI = 500116
Global Const ID_PRODUKSI_MAINMENU_TABLES_REAKTOR = 500117

Global Const ID_PRODUKSI_MAINMENU_SOP = 50013
Global Const ID_PRODUKSI_MAINMENU_SOP_ADD = 500131
Global Const ID_PRODUKSI_MAINMENU_SOP_ADD_NEW = 5001311
Global Const ID_PRODUKSI_MAINMENU_SOP_ADD_EDIT = 5001312

Global Const ID_PRODUKSI_MAINMENU_SOP_CHANGE = 500132
Global Const ID_PRODUKSI_MAINMENU_SOP_LIST = 500133
Global Const ID_PRODUKSI_MAINMENU_SOP_LISTSTOKBAHANBAKU = 500134
Global Const ID_PRODUKSI_MAINMENU_SOP_LOTPALET = 500135
Global Const ID_PRODUKSI_MAINMENU_SOP_LISTGROUP = 500136
Global Const ID_PRODUKSI_MAINMENU_SOP_SCANLOT = 500137
Global Const ID_PRODUKSI_MAINMENU_SOP_PRODMONTHLY = 500138

Global Const ID_PRODUKSI_MAINMENU_SOP_TAKEPACKAGE = 500139
Global Const ID_PRODUKSI_MAINMENU_SOP_TAKEPACKAGE_ADD = 5001391
Global Const ID_PRODUKSI_MAINMENU_SOP_TAKEPACKAGE_LIST = 5001392
Global Const ID_PRODUKSI_MAINMENU_SOP_TAKEPACKAGE_REPORT = 5001393

Global Const ID_PRODUKSI_MAINMENU_SOP_SCANLOT_SCANPALET = 5001371
Global Const ID_PRODUKSI_MAINMENU_SOP_SCANLOT_EDITPALET = 5001372
Global Const ID_PRODUKSI_MAINMENU_SOP_SCANLOT_KEYPALET = 5001373
Global Const ID_PRODUKSI_MAINMENU_SOP_PRODMONTHLY_BYBB = 5001381
Global Const ID_PRODUKSI_MAINMENU_SOP_PRODMONTHLY_BYTOPPRODUK = 5001382
Global Const ID_PRODUKSI_MAINMENU_SOP_RFID = 500140
Global Const ID_PRODUKSI_MAINMENU_PRINTETIKET = 50014
Global Const ID_PRODUKSI_MAINMENU_MUTASI = 50015
Global Const ID_PRODUKSI_MAINMENU_MUTASI_ADD = 500151
Global Const ID_PRODUKSI_MAINMENU_MUTASI_LAPLOT = 500152
Global Const ID_PRODUKSI_MAINMENU_MUTASI_WIPBASE = 500153
Global Const ID_PRODUKSI_MAINMENU_MUTASI_LAPWIPBASE = 500154
Global Const ID_PRODUKSI_MAINMENU_MUTASI_ADJWIP = 500155


'####################################### ID GUDANG #############################
Global Const ID_GUDANG = 700
Global Const ID_GUDANG_MAINMENU = 7001


Public RibbonBar As RibbonBar

Public CtrlFile As CommandBarPopup
Public FILE_CHANGEPAS As CommandBarButton
Public FILE_DASHBOARD As CommandBarButton
Public FILE_LOGOUT As CommandBarButton

'########################## SET MASTER #########################
Public MASTER As RibbonTab
Public MASTER_DATABASE As RibbonGroup
Public MASTER_DATABASE_KONEKSI As CommandBarButton
Public MASTER_DATABASE_KONEKSISQL As CommandBarButton
Public MASTER_DATABASE_KONEKSI_BACKUP As CommandBarButton
Public MASTER_DATABASE_KONEKSI_RESTORE As CommandBarButton
Public MASTER_DATABASE_MAINTENANCE As RibbonGroup
Public MASTER_DATABASE_MAINTENANCE_IMPORTBAHANBAKU As CommandBarButton
Public MASTER_DATABASE_MAINTENANCE_IMPORTBARANGJADI As CommandBarButton
Public MASTER_DATABASE_MAINTENANCE_BROADCASTMESSAGE As CommandBarButton

Public MASTER_MANAGEUSER As RibbonGroup
Public MASTER_MANAGEUSER_USER As CommandBarButton
Public MASTER_MANAGEUSER_DEPARTEMEN As CommandBarButton
Public MASTER_MANAGEUSER_MODUL As CommandBarButton
Public MASTER_MANAGEUSER_LEVEL As CommandBarButton
Public MASTER_MANAGEUSER_USERDEPT As CommandBarButton

Public MASTER_TELEGRAM As RibbonGroup
Public MASTER_TELEGRAM_BOT As CommandBarButton

Public MASTER_MAINTENACE As RibbonGroup

'#################################### SET HRD ###########################
Public PERSONALIA As RibbonTab

'#################################### SET PEMBELIAN #####################
Public PEMBELIAN As RibbonTab
Public PEMBELIAN_MAINMENU As RibbonGroup
Public PEMBELIAN_TABEL As CommandBarPopup

Public PEMBELIAN_TABEL_SUPPLIER As CommandBarPopup
Public PEMBELIAN_TABEL_SUPPLIER_ADD As CommandBarButton
Public PEMBELIAN_TABEL_SUPPLIER_CHANGE As CommandBarButton
Public PEMBELIAN_TABEL_SUPPLIER_LIST As CommandBarButton
Public PEMBELIAN_TABEL_SUPPLIER_IMPORTEXPORT As CommandBarButton
Public PEMBELIAN_TABEL_SUPPLIER_PRICELIST As CommandBarButton
Public PEMBELIAN_TABEL_SUPPLIER_GRAPRICE As CommandBarButton

Public PEMBELIAN_TABEL_SATUAN As CommandBarPopup
Public PEMBELIAN_TABEL_SATUAN_ADD As CommandBarButton
Public PEMBELIAN_TABEL_SATUAN_CHANGE As CommandBarButton
Public PEMBELIAN_TABEL_SATUAN_IMPORTEXPORT As CommandBarButton
Public PEMBELIAN_TABEL_SATUAN_LIST As CommandBarButton

Public PEMBELIAN_TABEL_BAHANBAKU As CommandBarPopup
Public PEMBELIAN_TABEL_BAHANBAKU_MANAGE As CommandBarButton
Public PEMBELIAN_TABEL_BAHANBAKU_IMPORTEXPORT As CommandBarButton
Public PEMBELIAN_TABEL_BAHANBAKU_LIST As CommandBarButton

Public PEMBELIAN_TABEL_CUR As CommandBarPopup
Public PEMBELIAN_TABEL_CUR_ADD As CommandBarButton
Public PEMBELIAN_TABEL_CUR_CHANGE As CommandBarButton
Public PEMBELIAN_TABEL_CUR_IMPORTEXPORT As CommandBarButton
Public PEMBELIAN_TABEL_CUR_LIST As CommandBarButton

'Public PEMBELIAN_TABEL_BANK As CommandBarPopup
'Public PEMBELIAN_TABEL_BANK_ADD As CommandBarButton
'Public PEMBELIAN_TABEL_BANK_CHANGE As CommandBarButton
'Public PEMBELIAN_TABEL_BANK_IMPORTEXPORT As CommandBarButton
'Public PEMBELIAN_TABEL_BANK_LIST As CommandBarButton

Public PEMBELIAN_TABEL_PACKAGING As CommandBarPopup
Public PEMBELIAN_TABEL_PACKAGING_ADD As CommandBarButton
Public PEMBELIAN_TABEL_PACKAGING_CHANGE As CommandBarButton

Public PEMBELIAN_TABEL_MINSTOCK As CommandBarPopup
Public PEMBELIAN_TABEL_MINSTOCK_ADD As CommandBarButton
Public PEMBELIAN_TABEL_MINSTOCK_CHANGE As CommandBarButton
Public PEMBELIAN_TABEL_MINSTOCK_LIST As CommandBarButton

Public PEMBELIAN_MUTASIBARANG As CommandBarPopup
Public PEMBELIAN_MUTASIBARANG_ADD As CommandBarButton
Public PEMBELIAN_MUTASIBARANG_CHANGE As CommandBarButton
Public PEMBELIAN_MUTASIBARANG_IMPORTEXPORT As CommandBarButton
Public PEMBELIAN_MUTASIBARANG_LIST As CommandBarButton
Public PEMBELIAN_MUTASIBARANG_BASE As CommandBarButton

Public PEMBELIAN_PURCHASING As CommandBarPopup
Public PEMBELIAN_PURCHASING_PO As CommandBarPopup
Public PEMBELIAN_PURCHASING_PO_ADD As CommandBarButton
Public PEMBELIAN_PURCHASING_PO_CHANGE As CommandBarButton
Public PEMBELIAN_PURCHASING_PO_IMPORTEXPORT As CommandBarButton
Public PEMBELIAN_PURCHASING_PO_CLOSECANCEL As CommandBarButton

Public PEMBELIAN_PURCHASING_PENERIMAANBARANG As CommandBarPopup
Public PEMBELIAN_PURCHASING_PENERIMAANBARANG_ADD As CommandBarButton
Public PEMBELIAN_PURCHASING_PENERIMAANBARANG_CHANGE As CommandBarButton
Public PEMBELIAN_PURCHASING_PENERIMAANBARANG_IMPORTEXPORT As CommandBarButton
Public PEMBELIAN_PURCHASING_PENERIMAANBARANG_RETUR  As CommandBarButton
Public PEMBELIAN_PURCHASING_PENERIMAANBARANG_PRINTBPB As CommandBarButton

Public PEMBELIAN_PURCHASING_PEMAKAIANBAHANBAKU As CommandBarPopup
Public PEMBELIAN_PURCHASING_PEMAKAIANBAHANBAKU_ADD As CommandBarButton
Public PEMBELIAN_PURCHASING_PEMAKAIANBAHANBAKU_CHANGE As CommandBarButton
Public PEMBELIAN_PURCHASING_PEMAKAIANBAHANBAKU_IMPORTEXPORT As CommandBarButton
Public PEMBELIAN_PURCHASING_PEMAKAIANBAHANBAKU_SISA As CommandBarButton

Public PEMBELIAN_PURCHASING_CONFIRM As CommandBarPopup
Public PEMBELIAN_PURCHASING_CONFIRM_CONFIRMPENERIMAANBARANG As CommandBarPopup
Public PEMBELIAN_PURCHASING_CONFIRM_CONFIRMPENERIMAANBARANG_ADD As CommandBarButton
Public PEMBELIAN_PURCHASING_CONFIRM_CONFIRMPENERIMAANBARANG_REPRINT As CommandBarButton
Public PEMBELIAN_PURCHASING_CONFIRM_CONFIRMRETURPENERIMAANBARANG As CommandBarButton
Public PEMBELIAN_PURCHASING_CONFIRM_UNCONFIRMPENRIMAANBARANG As CommandBarButton
Public PEMBELIAN_PURCHASING_CONFIRM_UNCONFIRMRETURPENERIMAANBARANG As CommandBarButton
Public PEMBELIAN_PURCHASING_CONFIRM_CREATEVOUCHER As CommandBarButton

Public PEMBELIAN_PURCHASING_INQUIRY As CommandBarButton
Public PEMBELIAN_PURCHASING_PRINTPO As CommandBarButton
Public PEMBELIAN_PURCHASING_LAPPO As CommandBarButton
Public PEMBELIAN_PURCHASING_LAPPEMAKAIANBB As CommandBarButton
Public PEMBELIAN_PURCHASING_LAPPEMBELIAN As CommandBarButton
Public PEMBELIAN_PURCHASING_LAPCONPEMBELIAN As CommandBarButton
Public PEMBELIAN_PURCHASING_LAPVOUCER As CommandBarButton
Public PEMBELIAN_PURCHASING_LAPPROSESVOUCHER As CommandBarButton

Public PEMBELIAN_PURCHASING_PERMINTAAN As CommandBarPopup
Public PEMBELIAN_PURCHASING_PERMINTAAN_ADD As CommandBarButton
Public PEMBELIAN_PURCHASING_PERMINTAAN_CHANGE As CommandBarButton
Public PEMBELIAN_PURCHASING_PERMINTAAN_CLOSE As CommandBarButton
Public PEMBELIAN_PURCHASING_PERMINTAAN_LIST As CommandBarButton
Public PEMBELIAN_PURCHASING_PERMINTAAN_DAYSCOUNT As CommandBarButton
Public PEMBELIAN_PURCHASING_PERMINTAAN_PRINT As CommandBarButton

Public PEMBELIAN_HUTANG As CommandBarPopup
Public PEMBELIAN_HUTANG_PBYHUTANG As CommandBarPopup
Public PEMBELIAN_HUTANG_PBYHUTANG_ADD As CommandBarButton
Public PEMBELIAN_HUTANG_PBYHUTANG_CHANGE As CommandBarButton
Public PEMBELIAN_HUTANG_PBYHUTANG_UNPOST As CommandBarButton
Public PEMBELIAN_HUTANG_KOREKSIHTNG As CommandBarPopup
Public PEMBELIAN_HUTANG_KOREKSIHTNG_ADD As CommandBarButton
Public PEMBELIAN_HUTANG_KOREKSIHTNG_CHANGE As CommandBarButton
Public PEMBELIAN_HUTANG_LISTKOREKSI As CommandBarButton
Public PEMBELIAN_HUTANG_LISTPBYHUTANG As CommandBarButton
Public PEMBELIAN_HUTANG_LAPSISAHUTANG As CommandBarButton
Public PEMBELIAN_HUTANG_LAPBYJT As CommandBarButton


Public PEMBELIAN_GIRO As CommandBarPopup
Public PEMBELIAN_UTILITY As CommandBarPopup
Public PEMBELIAN_UTILITY_FASTSEARCH As CommandBarCheckBox
Public PEMBELIAN_UTILITY_ADJUSTSTOK As CommandBarButton
Public PEMBELIAN_UTILITY_EXPORTDATAPABRIK  As CommandBarButton
Public PEMBELIAN_UTILITY_IMPORTDATA As CommandBarButton
Public PEMBELIAN_UTILITY_OPTIONS As CommandBarButton

'###################################### KEUANGAN ID ###########################
Global Const ID_KEUANGAN = 400
Global Const ID_KEUANGAN_MAINMENU = 4001
Global Const ID_KEUANGAN_TABLE = 40011
Global Const ID_KEUANGAN_PEMBELIAN = 40012
Global Const ID_KEUANGAN_PEMBELIAN_HTNGKARTU = 400121
Global Const ID_KEUANGAN_PEMBELIAN_MAINTENACEGIRO = 400122
Global Const ID_KEUANGAN_PEMBELIAN_ADDGIROTOLAK = 400123
Global Const ID_KEUANGAN_PEMBELIAN_CHANGEGIROTOLAK = 400124
Global Const ID_KEUANGAN_PEMBELIAN_LAPGIRO = 400125
Global Const ID_KEUANGAN_PEMBELIAN_UTILITY = 40013
Global Const ID_KEUANGAN_PEMBELIAN_PERIODONPROSES = 400131
Global Const ID_KEUANGAN_PEMBELIAN_UTILITY_DEFINEACCOUNTSUPPLIER = 400132
Global Const ID_KEUANGAN_PEMBELIAN_UTILITY_DEFINEBANKKAS = 400133
Global Const ID_KEUANGAN_PEMBELIAN_UTILITY_DEFINEJURNALANDPROSES = 400134
Global Const ID_KEUANGAN_PEMBELIAN_UTILITY_LAPORANPOSTING = 400135

Global Const ID_KEUANGAN_PENJUALAN = 4002
Global Const ID_KEUANGAN_PENJUALAN_PIUTANG = 40021
Global Const ID_KEUANGAN_PENJUALAN_PIUTANG_KOREKSIPIUTANG = 400211
Global Const ID_KEUANGAN_PENJUALAN_PIUTANG_KOREKSIPIUTANG_ADD = 4002111
Global Const ID_KEUANGAN_PENJUALAN_PIUTANG_KOREKSIPIUTANG_CHANGE = 4002112
Global Const ID_KEUANGAN_PENJUALAN_PIUTANG_KOREKSIPIUTANG_WRITEOFF = 4002113
Global Const ID_KEUANGAN_PENJUALAN_PIUTANG_PEMBAYARAN = 40022
Global Const ID_KEUANGAN_PENJUALAN_PIUTANG_PEMBAYARAN_ADD = 400221
Global Const ID_KEUANGAN_PENJUALAN_PIUTANG_PEMBAYARAN_CHANGE = 400222
Global Const ID_KEUANGAN_PENJUALAN_PIUTANG_DAFTARKOREKSIPIUTANG = 40023
Global Const ID_KEUANGAN_PENJUALAN_PIUTANG_LAPPENAGIHAN = 40024
Global Const ID_KEUANGAN_PENJUALAN_PIUTANG_LAPPIUTANGAGING = 40025
Global Const ID_KEUANGAN_PENJUALAN_PIUTANG_LAPKARTUPIUTANG = 40026
Global Const ID_KEUANGAN_PENJUALAN_PIUTANG_LAPSISAPIUTANG = 40027
Global Const ID_KEUANGAN_PENJUALAN_PIUTANG_LAPPEMBAYARAN = 40028
Global Const ID_KEUANGAN_PENJUALAN_PIUTANG_LAPPEMBAYARANDTL = 40029
Global Const ID_KEUANGAN_PENJUALAN_PIUTANG_LAPTANDATERIMAPBY = 400291
Global Const ID_KEUANGAN_PENJUALAN_PIUTANG_LAPMUTPIUTANG = 40030
Global Const ID_KEUANGAN_PENJUALAN_GIRO = 40023
Global Const ID_KEUANGAN_PENJUALAN_GIRO_MAINTENANCE = 400231
Global Const ID_KEUANGAN_PENJUALAN_GIRO_GANTIGIROTOLAK = 400232
Global Const ID_KEUANGAN_PENJUALAN_GIRO_GANTIGIROTOLAK_ADD = 4002321
Global Const ID_KEUANGAN_PENJUALAN_GIRO_GANTIGIROTOLAK_CHANGE = 4002322
Global Const ID_KEUANGAN_PENJUALAN_GIRO_LAPGIRO = 400233
Global Const ID_KEUANGAN_PENJUALAN_GIRO_LISTAPPGIROTOLAK = 400234
Global Const ID_KEUANGAN_PENJUALAN_UTILITY = 40024
Global Const ID_KEUANGAN_PENJUALAN_UTILITY_PERIODONPROSES = 400241
Global Const ID_KEUANGAN_PENJUALAN_UTILITY_DEFAINACCBANKCASH = 400242
Global Const ID_KEUANGAN_PENJUALAN_UTILITY_DEFAINJURNAL = 400243
Global Const ID_KEUANGAN_PENJUALAN_UTILITY_DEFINEAGING = 400244
Global Const ID_KEUANGAN_PENJUALAN_UTILITY_DEFINEKG = 400245
Global Const ID_KEUANGAN_PENJUALAN_UTILITY_DEFINECOSUTOMERACC = 400246
Global Const ID_KEUANGAN_PENJUALAN_UTILITY_LAPPOSTINGPENJUALAN = 400247
Global Const ID_KEUANGAN_PENJUALAN_UTILITY_LISTKG = 400248
Public KEUANGAN_PENJUALAN_UTILITY_LISTKG As CommandBarButton

Global Const ID_KEUANGAN_GL = 4003
Global Const ID_KEUANGAN_GL_TABEL = 40031
Global Const ID_KEUANGAN_GL_TABEL_COMPANYTYPE = 400311
Global Const ID_KEUANGAN_GL_TABEL_COMPANYTYPE_ADD = 4003111
Global Const ID_KEUANGAN_GL_TABEL_COMPANYTYPE_UPDATE = 4003112
Global Const ID_KEUANGAN_GL_TABEL_COMPANYTYPE_LIST = 4003113
Global Const ID_KEUANGAN_GL_TABEL_MASTERACC = 4003112
Global Const ID_KEUANGAN_GL_TABEL_MASTERACC_ADD = 40031121
Global Const ID_KEUANGAN_GL_TABEL_MASTERACC_UPDATE = 40031122
Global Const ID_KEUANGAN_GL_TABEL_MASTERACC_LIST = 40031123
Global Const ID_KEUANGAN_GL_TABEL_COMPANYIDENTIFICATION = 4003113
Global Const ID_KEUANGAN_GL_TABEL_COMPANYIDENTIFICATION_ADD = 40031131
Global Const ID_KEUANGAN_GL_TABEL_COMPANYIDENTIFICATION_UPDATE = 40031132
Global Const ID_KEUANGAN_GL_TABEL_COMPANYIDENTIFICATION_LIST = 40031133
Global Const ID_KEUANGAN_GL_TABEL_COMPANYACCOUNT = 4003114
Global Const ID_KEUANGAN_GL_TABEL_COMPANYACCOUNT_BROWSE = 40031141
Global Const ID_KEUANGAN_GL_TABEL_COMPANYACCOUNT_LISTACCOUNT = 40031142
Global Const ID_KEUANGAN_GL_TABEL_COMPANYACCOUNT_LISTBUDGET = 40031143
Global Const ID_KEUANGAN_GL_TABEL_CURRENCY = 4003115
Global Const ID_KEUANGAN_GL_TABEL_CURRENCY_ADD = 40031151
Global Const ID_KEUANGAN_GL_TABEL_CURRENCY_UPDATE = 40031152
Global Const ID_KEUANGAN_GL_TABEL_CURRENCY_LIST = 40031153
Global Const ID_KEUANGAN_GL_TABEL_FIXEDASSETTYPE = 4003116
Global Const ID_KEUANGAN_GL_TABEL_FIXEDASSETTYPE_ADD = 40031161
Global Const ID_KEUANGAN_GL_TABEL_FIXEDASSETTYPE_UPDATE = 40031162
Global Const ID_KEUANGAN_GL_TABEL_FIXEDASSETTYPE_LIST = 40031163
Global Const ID_KEUANGAN_GL_TABEL_BANK = 4003117
Global Const ID_KEUANGAN_GL_TABEL_BANK_ADD = 40031171
Global Const ID_KEUANGAN_GL_TABEL_BANK_UPDATE = 40031172
Global Const ID_KEUANGAN_GL_TABEL_BANK_LIST = 40031173

Global Const ID_KEUANGAN_GL_FIXEDASSET = 40032
Global Const ID_KEUANGAN_GL_FIXEDASSET_PEMBELIANFIXEDASSET = 400321
Global Const ID_KEUANGAN_GL_FIXEDASSET_POSTINGPEMBELIANFIXEDASSET = 400322
Global Const ID_KEUANGAN_GL_FIXEDASSET_UNPOSTINGPEMBELIANFIXEDASSET = 400323
Global Const ID_KEUANGAN_GL_FIXEDASSET_PENJUALANFIXEDASSET = 400324
Global Const ID_KEUANGAN_GL_FIXEDASSET_POSTINGPENJUALANFIXEDASSET = 400325
Global Const ID_KEUANGAN_GL_FIXEDASSET_UNPOSTINGPENJUALANFIXEDASSET = 400326

Global Const ID_KEUANGAN_GL_LEDGER = 40033
Global Const ID_KEUANGAN_GL_LEDGER_JURNAL = 400331
Global Const ID_KEUANGAN_GL_LEDGER_JURNAL_ADD = 4003311
Global Const ID_KEUANGAN_GL_LEDGER_JURNAL_UPDATE = 4003312
Global Const ID_KEUANGAN_GL_LEDGER_JURNAL_LIST = 4003313
Global Const ID_KEUANGAN_GL_LEDGER_JURNAL_POSTING = 4003314
Global Const ID_KEUANGAN_GL_LEDGER_JURNAL_UNPOSTING = 4003315
Global Const ID_KEUANGAN_GL_LEDGER_CAHBANKIN = 400332

Global Const ID_KEUANGAN_GL_LEDGER_CAHBANKIN_ADD = 4003321
Global Const ID_KEUANGAN_GL_LEDGER_CAHBANKIN_UPDATE = 4003322
Global Const ID_KEUANGAN_GL_LEDGER_CAHBANKIN_LIST = 4003323
Global Const ID_KEUANGAN_GL_LEDGER_CAHBANKIN_POSTING = 4003324
Global Const ID_KEUANGAN_GL_LEDGER_CAHBANKIN_UNPOSTING = 4003325

Global Const ID_KEUANGAN_GL_LEDGER_CAHBANKOUT = 400333
Global Const ID_KEUANGAN_GL_LEDGER_CAHBANKOUT_ADD = 4003331
Global Const ID_KEUANGAN_GL_LEDGER_CAHBANKOUT_ADD_NEW = 40033311
Global Const ID_KEUANGAN_GL_LEDGER_CAHBANKOUT_ADD_OLD = 40033312
Global Const ID_KEUANGAN_GL_LEDGER_CAHBANKOUT_UPDATE = 4003332
Global Const ID_KEUANGAN_GL_LEDGER_CAHBANKOUT_LIST = 40003333
Global Const ID_KEUANGAN_GL_LEDGER_CAHBANKOUT_POSTING = 40003334
Global Const ID_KEUANGAN_GL_LEDGER_CAHBANKOUT_UNPOSTING = 40003335
Global Const ID_KEUANGAN_GL_LEDGER_BUKTIKELUAR = 4000334
Global Const ID_KEUANGAN_GL_LEDGER_BUKTIKELUAR_ADD = 40003341
Global Const ID_KEUANGAN_GL_LEDGER_BUKTIKELUAR_LIST = 40003342
Global Const ID_KEUANGAN_GL_LEDGER_BUKTIKELUAR_NEW = 40003343
Global Const ID_KEUANGAN_GL_LEDGER_BUKTIKELUAR_UPDATE = 40003344
Global Const ID_KEUANGAN_GL_LEDGER_BUKTIKELUAR_REPRINT = 40003345
Global Const ID_KEUANGAN_GL_LEDGER_CAHBANKOUT_PRINT = 40003337
Global Const ID_KEUANGAN_GL_LEDGER_ETOL = 40003338

Global Const ID_KEUANGAN_GL_REPORT = 40034
Global Const ID_KEUANGAN_GL_REPORT_TRIALBALANCE = 400341
Global Const ID_KEUANGAN_GL_REPORT_BUKUBESAR = 400342
Global Const ID_KEUANGAN_GL_REPORT_WORKSHEET = 400343
Global Const ID_KEUANGAN_GL_REPORT_DAILYCASHFLOW = 400344
Global Const ID_KEUANGAN_GL_REPORT_BALANCESHEET = 4000345
Global Const ID_KEUANGAN_GL_REPORT_INCOMESTATEMENT = 400346
Global Const ID_KEUANGAN_GL_REPORT_DAFTARFIXEDASSET = 400347
Global Const ID_KEUANGAN_GL_REPORT_NILAIFIXEDASSET = 400348
Global Const ID_KEUANGAN_GL_REPORT_PENJUALANFIXEDASSET = 400349

Global Const ID_KEUANGAN_GL_UTILITY = 40035
Global Const ID_KEUANGAN_GL_UTILITY_UNBALANCETRANS = 400351
Global Const ID_KEUANGAN_GL_UTILITY_IMPORT = 400352
Global Const ID_KEUANGAN_GL_UTILITY_EXPORT = 400353
Global Const ID_KEUANGAN_GL_UTILITY_RESETSALDO = 400354
Global Const ID_KEUANGAN_GL_UTILITY_SETUPLAYOUTREPORT = 400355
Global Const ID_KEUANGAN_GL_UTILITY_SETUPLAYOUTREPORT_DEFINE = 4003551
Global Const ID_KEUANGAN_GL_UTILITY_SETUPLAYOUTREPORT_LIST = 4003552
Global Const ID_KEUANGAN_GL_UTILITY_SETUPLAYOUTREPORT_CROSS = 4003553
Global Const ID_KEUANGAN_GL_UTILITY_CLOSING = 400356
Global Const ID_KEUANGAN_GL_UTILITY_UNCLOSING = 40357
Global Const ID_KEUANGAN_GL_UTILITY_REKONSILIASI = 40358

'######################################## SET KEUANGAN ###############################
Public KEUANGAN As RibbonTab
Public KEUANGAN_MAINMENU As RibbonGroup
Public KEUANGAN_GL As RibbonGroup
Public KEUANGAN_TABLE As CommandBarPopup
Public KEUANGAN_PEMBELIAN As CommandBarPopup
Public KEUANGAN_PEMBELIAN_HTNGKARTU As CommandBarButton
Public KEUANGAN_PEMBELIAN_MAINTENACEGIRO As CommandBarButton
Public KEUANGAN_PEMBELIAN_ADDGIROTOLAK As CommandBarButton
Public KEUANGAN_PEMBELIAN_CHANGEGIROTOLAK As CommandBarButton
Public KEUANGAN_PEMBELIAN_LAPGIRO As CommandBarButton
Public KEUANGAN_PEMBELIAN_UTILITY As CommandBarPopup
Public KEUANGAN_PEMBELIAN_PERIODONPROSES As CommandBarButton
Public KEUANGAN_PEMBELIAN_UTILITY_DEFINEACCOUNTSUPPLIER As CommandBarButton
Public KEUANGAN_PEMBELIAN_UTILITY_DEFINEBANKKAS As CommandBarButton
Public KEUANGAN_PEMBELIAN_UTILITY_DEFINEJURNALANDPROSES As CommandBarButton
Public KEUANGAN_PEMBELIAN_UTILITY_LAPORANPOSTING As CommandBarButton


Public KEUANGAN_PENJUALAN As CommandBarPopup
Public KEUANGAN_PENJUALAN_PIUTANG As CommandBarPopup
Public KEUANGAN_PENJUALAN_PIUTANG_KOREKSI As CommandBarPopup
Public KEUANGAN_PENJUALAN_PIUTANG_KOREKSI_ADD As CommandBarButton
Public KEUANGAN_PENJUALAN_PIUTANG_KOREKSI_CHANGE As CommandBarButton
Public KEUANGAN_PENJUALAN_PIUTANG_KOREKSI_WRITEOFF As CommandBarButton
Public KEUANGAN_PENJUALAN_PIUTANG_PEMBAYARAN As CommandBarPopup
Public KEUANGAN_PENJUALAN_PIUTANG_PEMBAYARAN_ADD As CommandBarButton
Public KEUANGAN_PENJUALAN_PIUTANG_PEMBAYARAN_CHANGE As CommandBarButton
Public KEUANGAN_PENJUALAN_PIUTANG_DAFTARKOREKSIPIUTANG As CommandBarButton
Public KEUANGAN_PENJUALAN_PIUTANG_LAPPENAGIHAN As CommandBarButton
Public KEUANGAN_PENJUALAN_PIUTANG_LAPPIUTANGAGING As CommandBarButton
Public KEUANGAN_PENJUALAN_PIUTANG_LAPKARTUPIUTANG As CommandBarButton
Public KEUANGAN_PENJUALAN_PIUTANG_LAPSISAUTANG As CommandBarButton
Public KEUANGAN_PENJUALAN_PIUTANG_LAPPEMBAYARAN As CommandBarButton
Public KEUANGAN_PENJUALAN_PIUTANG_LAPPEMBAYARANDTL As CommandBarButton
Public KEUANGAN_PENJUALAN_PIUTANG_LAPTANDATERIMAPBY As CommandBarButton
Public KEUANGAN_PENJUALAN_PIUTANG_LAPMUTPIUTANG As CommandBarButton

Public KEUANGAN_PENJUALAN_GIRO As CommandBarPopup
Public KEUANGAN_PENJUALAN_GIRO_MAINTENANCE As CommandBarButton
Public KEUANGAN_PENJUALAN_GIRO_GANTIGIROTOLAK As CommandBarPopup
Public KEUANGAN_PENJUALAN_GIRO_GANTIGIROTOLAK_ADD As CommandBarButton
Public KEUANGAN_PENJUALAN_GIRO_GANTIGIROTOLAK_CHANGE As CommandBarButton
Public KEUANGAN_PENJUALAN_GIRO_LAPGIRO As CommandBarButton
Public KEUANGAN_PENJUALAN_GIRO_LISTAPPGANTIGIROTAL As CommandBarButton

Public KEUANGAN_PENJUALAN_UTILITY As CommandBarPopup
Public KEUANGAN_PENJUALAN_UTILITY_PERIODONPROSES As CommandBarButton
Public KEUANGAN_PENJUALAN_UTILITY_DEFAINACCBANKCASH As CommandBarButton
Public KEUANGAN_PENJUALAN_UTILITY_DEFINEJURNAL As CommandBarButton
Public KEUANGAN_PENJUALAN_UTILITY_DEFINEAGING As CommandBarButton
Public KEUANGAN_PENJUALAN_UTILITY_DEFINEKG As CommandBarButton
Public KEUANGAN_PENJUALAN_UTILITY_DEFINECOSUTOMERACC As CommandBarButton
Public KEUANGAN_PENJUALAN_UTILITY_LAPPOSTINGPENJUALAN As CommandBarButton

'General Ledger Variable
Public KEUANGAN_GL_TABEL As CommandBarPopup
Public KEUANGAN_GL_TABEL_COMPANYTYPE As CommandBarPopup
Public KEUANGAN_GL_TABLE_COMPANYTYPE_ADD As CommandBarButton
Public KEUANGAN_GL_TABEL_COMPANYTYPE_UPDATE As CommandBarButton
Public KEUANGAN_GL_TABEL_COMPANYTYPE_LIST As CommandBarButton
Public KEUANGAN_GL_TABEL_MASTERACC As CommandBarPopup
Public KEUANGAN_GL_TABEL_MASTERACC_ADD As CommandBarButton
Public KEUANGAN_GL_TABEL_MASTERACC_UPDATE As CommandBarButton
Public KEUANGAN_GL_TABEL_MASTERACC_LIST As CommandBarButton
Public KEUANGAN_GL_TABEL_COMPANYIDENTIFICATION As CommandBarPopup
Public KEUANGAN_GL_TABEL_COMPANYIDENTIFICATION_ADD As CommandBarButton
Public KEUANGAN_GL_TABEL_COMPANYIDENTIFICATION_UPDATE As CommandBarButton
Public KEUANGAN_GL_TABEL_COMPANYIDENTIFICATION_LIST As CommandBarButton

Public KEUANGAN_GL_TABEL_COMPANYACCOUNT As CommandBarPopup
Public KEUANGAN_GL_TABEL_COMPANYACCOUNT_BROWSE As CommandBarButton
Public KEUANGAN_GL_TABEL_COMPANYACCOUNT_LISTACOOUNT As CommandBarButton
Public KEUANGAN_GL_TABEL_COMPANYACCOUNT_LISTBUDGET As CommandBarButton

Public KEUANGAN_GL_TABEL_CURRENCY As CommandBarPopup
Public KEUANGAN_GL_TABEL_CURRENCY_ADD As CommandBarButton
Public KEUANGAN_GL_TABEL_CURRENCY_UPDATE As CommandBarButton
Public KEUANGAN_GL_TABEL_CURRENCY_LIST As CommandBarButton

Public KEUANGAN_GL_TABEL_FIXEDASSETTYPE As CommandBarPopup
Public KEUANGAN_GL_TABEL_FIXEDASSETTYPE_ADD As CommandBarButton
Public KEUANGAN_GL_TABEL_FIXEDASSETTYPE_UPDATE As CommandBarButton
Public KEUANGAN_GL_TABEL_FIXEDASSETTYPE_LIST As CommandBarButton

Public KEUANGAN_GL_TABEL_BANK As CommandBarPopup
Public KEUANGAN_GL_TABEL_BANK_ADD As CommandBarButton
Public KEUANGAN_GL_TABEL_BANK_UPDATE As CommandBarButton
Public KEUANGAN_GL_TABEL_BANK_LIST As CommandBarButton

Public KEUANGAN_GL_FIXEDASSET As CommandBarPopup
Public KEUANGAN_GL_FIXEDASSET_PEMBELIANASSET As CommandBarButton
Public KEUANGAN_GL_FIXEDASSET_POSTINGPEMBELIANFIXEDASSET As CommandBarButton
Public KEUANGAN_GL_FIXEDASSET_UNPOSTINGPEMBELIANFIXEDASSET As CommandBarButton

Public KEUANGAN_GL_FIXEDASSET_PENJUALANASSET As CommandBarButton
Public KEUANGAN_GL_FIXEDASSET_POSTINGPENJUALANFIXEDASSET As CommandBarButton
Public KEUANGAN_GL_FIXEDASSET_UNPOSTINGPENJUALANFIXEDASSET As CommandBarButton

Public KEUANGAN_GL_LEDGER As CommandBarPopup
Public KEUANGAN_GL_LEDGER_JURNAL  As CommandBarPopup
Public KEUANGAN_GL_LEDGER_CASHBANKIN As CommandBarPopup
Public KEUANGAN_GL_LEDGER_CASHBANKOUT As CommandBarPopup

Public KEUANGAN_GL_LEDGER_JURNAL_ADD As CommandBarButton
Public KEUANGAN_GL_LEDGER_JURNAL_UPDATE As CommandBarButton
Public KEUANGAN_GL_LEDGER_JURNAL_LIST As CommandBarButton
Public KEUANGAN_GL_LEDGER_JURNAL_POSTING As CommandBarButton
Public KEUANGAN_GL_LEDGER_JURNAL_UNPOSTING As CommandBarButton

Public KEUANGAN_GL_LEDGER_CAHBANKIN_ADD As CommandBarButton
Public KEUANGAN_GL_LEDGER_CAHBANKIN_UPDATE  As CommandBarButton
Public KEUANGAN_GL_LEDGER_CAHBANKIN_LIST As CommandBarButton
Public KEUANGAN_GL_LEDGER_CAHBANKIN_POSTING As CommandBarButton
Public KEUANGAN_GL_LEDGER_CAHBANKIN_UNPOSTING As CommandBarButton

Public KEUANGAN_GL_LEDGER_CAHBANKOUT_ADD As CommandBarPopup
Public KEUANGAN_GL_LEDGER_CAHBANKOUT_ADD_NEW As CommandBarButton
Public KEUANGAN_GL_LEDGER_CAHBANKOUT_ADD_OLD As CommandBarButton
Public KEUANGAN_GL_LEDGER_CAHBANKOUT_UPDATE As CommandBarButton
Public KEUANGAN_GL_LEDGER_CAHBANKOUT_LIST  As CommandBarButton
Public KEUANGAN_GL_LEDGER_CAHBANKOUT_POSTING As CommandBarButton
Public KEUANGAN_GL_LEDGER_CAHBANKOUT_UNPOSTING As CommandBarButton
Public KEUANGAN_GL_LEDGER_BUKTIKELUAR As CommandBarPopup
Public KEUANGAN_GL_LEDGER_BUKTIKELUAR_ADD As CommandBarButton
Public KEUANGAN_GL_LEDGER_BUKTIKELUAR_LIST As CommandBarButton
Public KEUANGAN_GL_LEDGER_BUKTIKELUAR_NEW As CommandBarButton
Public KEUANGAN_GL_LEDGER_BUKTIKELUAR_UPDATE As CommandBarButton
Public KEUANGAN_GL_LEDGER_BUKTIKELUAR_REPRINT As CommandBarButton
Public KEUANGAN_GL_LEDGER_CAHBANKOUT_PRINT As CommandBarButton
Public KEUANGAN_GL_LEDGER_ETOL As CommandBarButton

Public KEUANGAN_GL_REPORT As CommandBarPopup
Public KEUANGAN_GL_REPORT_TRIALBALANCE As CommandBarButton
Public KEUANGAN_GL_REPORT_BUKUBESAR As CommandBarButton
Public KEUANGAN_GL_REPORT_WORKSHEET As CommandBarButton
Public KEUANGAN_GL_REPORT_DAILYCASHFLOW As CommandBarButton
Public KEUANGAN_GL_REPORT_BALANCESHEET As CommandBarButton
Public KEUANGAN_GL_REPORT_INCOMESTATEMENT As CommandBarButton
Public KEUANGAN_GL_REPORT_DAFTARFIXEDASSET As CommandBarButton
Public KEUANGAN_GL_REPORT_NILAIFIXEDASSET As CommandBarButton
Public KEUANGAN_GL_REPORT_PENJUALANFIXEDASSET As CommandBarButton

Public KEUANGAN_GL_UTILITY As CommandBarPopup
Public KEUANGAN_GL_UTILITY_UNBALANCETRANS As CommandBarButton
Public KEUANGAN_GL_UTILITY_IMPORT As CommandBarButton
Public KEUANGAN_GL_UTILITY_EXPORT As CommandBarButton
Public KEUANGAN_GL_UTILITY_RESETSALDO As CommandBarButton
Public KEUANGAN_GL_UTILITY_SETUPLAYOUTREPORT As CommandBarPopup
Public KEUANGAN_GL_UTILITY_SETUPLAYOUTREPORT_DEFINE As CommandBarButton
Public KEUANGAN_GL_UTILITY_SETUPLAYOUTREPORT_LIST As CommandBarButton
Public KEUANGAN_GL_UTILITY_SETUPLAYOUTREPORT_CROSS As CommandBarButton
Public KEUANGAN_GL_UTILITY_CLOSING As CommandBarButton
Public KEUANGAN_GL_UTILITY_UNCLOSING As CommandBarButton
Public KEUANGAN_GL_UTILITY_REKONSILIASI As CommandBarButton


'######################################## SET PRODUKSI ###############################
Public PRODUKSI As RibbonTab
Public PRODUKSI_MAINMENU As RibbonGroup
Public PRODUKSI_MAINMENU_TABLES As CommandBarPopup
'Public PRODUKSI_MAINMENU_TABLES_REAKTOR As CommandBarPopup
'Public PRODUKSI_MAINMENU_TABLES_REAKTOR_ADD As CommandBarButton
'Public PRODUKSI_MAINMENU_TABLES_REAKTOR_CHANGE As CommandBarButton
Public PRODUKSI_MAINMENU_TABLES_RESEP As CommandBarPopup
Public PRODUKSI_MAINMENU_TABLES_RESEP_LEM As CommandBarButton
Public PRODUKSI_MAINMENU_TABLES_RESEP_KARET As CommandBarButton
Public PRODUKSI_MAINMENU_TABLES_RESEP_LISTLEM As CommandBarButton
Public PRODUKSI_MAINMENU_TABLES_KONVERSI As CommandBarPopup
Public PRODUKSI_MAINMENU_TABLES_KONVERSI_ADD As CommandBarButton
Public PRODUKSI_MAINMENU_TABLES_KONVERSI_CHANGE As CommandBarButton
Public PRODUKSI_MAINMENU_TABLES_KONVERSI_LIST As CommandBarButton
Public PRODUKSI_MAINMENU_TABLES_KONVERSI_UNIT As CommandBarButton
Public PRODUKSI_MAINMENU_TABLES_DEFINEKG As CommandBarButton
Public PRODUKSI_MAINMENU_TABLES_RNCPROD As CommandBarPopup
Public PRODUKSI_MAINMENU_TABLES_RNCPROD_ADD As CommandBarButton
Public PRODUKSI_MAINMENU_TABLES_RNCPROD_CHANGE As CommandBarButton
Public PRODUKSI_MAINMENU_TABLES_RNCPROD_LIST As CommandBarButton
Public PRODUKSI_MAINMENU_TABLES_KATEGORI As CommandBarButton
Public PRODUKSI_MAINMENU_TABLES_REAKTOR As CommandBarButton
Public PRODUKSI_MAINMENU_SOP As CommandBarPopup
Public PRODUKSI_MAINMENU_SOP_ADD As CommandBarPopup
Public PRODUKSI_MAINMENU_SOP_ADD_NEW As CommandBarButton
Public PRODUKSI_MAINMENU_SOP_ADD_EDIT As CommandBarButton

Public PRODUKSI_MAINMENU_SOP_TAKEPACKAGE As CommandBarPopup
Public PRODUKSI_MAINMENU_SOP_TAKEPACKAGE_ADD As CommandBarButton
Public PRODUKSI_MAINMENU_SOP_TAKEPACKAGE_LIST As CommandBarButton
Public PRODUKSI_MAINMENU_SOP_TAKEPACKAGE_REPORT As CommandBarButton

Public PRODUKSI_MAINMENU_SOP_CHANGE As CommandBarButton
Public PRODUKSI_MAINMENU_SOP_LIST As CommandBarButton
Public PRODUKSI_MAINMENU_SOP_LISTSTOKBAHANBAKU As CommandBarButton
Public PRODUKSI_MAINMENU_SOP_LOTPALET As CommandBarButton
Public PRODUKSI_MAINMENU_SOP_PRODMONTHLY As CommandBarPopup
Public PRODUKSI_MAINMENU_SOP_PRODMONTHLY_BYBB As CommandBarButton
Public PRODUKSI_MAINMENU_SOP_PRODMONTHLY_BYTOPPRODUK As CommandBarButton
Public PRODUKSI_MAINMENU_SOP_LISTGROUP As CommandBarButton
Public PRODUKSI_MAINMENU_SOP_SCANLOT As CommandBarPopup
Public PRODUKSI_MAINMENU_SOP_SCANLOT_SCANPALET As CommandBarButton
Public PRODUKSI_MAINMENU_SOP_SCANLOT_EDITPALET As CommandBarButton
Public PRODUKSI_MAINMENU_SOP_SCANLOT_KEYPALET As CommandBarButton
Public PRODUKSI_MAINMENU_SOP_RFID As CommandBarButton
Public PRODUKSI_MAINMENU_PRINTETIKET As CommandBarButton
Public PRODUKSI_MAINMENU_MUTASI As CommandBarPopup
Public PRODUKSI_MAINMENU_MUTASI_ADD As CommandBarButton
Public PRODUKSI_MAINMENU_MUTASI_LAPLOT As CommandBarButton
Public PRODUKSI_MAINMENU_MUTASI_WIPBASE As CommandBarButton
Public PRODUKSI_MAINMENU_MUTASI_LAPWIPBASE As CommandBarButton
Public PRODUKSI_MAINMENU_MUTASI_ADJWIP As CommandBarButton


'###################################### PENJUALAN ID ##########################
Global Const ID_PENJUALAN = 600
Global Const ID_PENJUALAN_MAINMENU = 6001
Global Const ID_PENJUALAN_MAINMENU_TABLE = 60011
Global Const ID_PENJUALAN_MAINMENU_TABLE_SATUAN = 600111
Global Const ID_PENJUALAN_MAINMENU_TABLE_SATUAN_ADD = 6001111
Global Const ID_PENJUALAN_MAINMENU_TABLE_SATUAN_CHANGE = 6001112
Global Const ID_PENJUALAN_MAINMENU_TABLE_SATUAN_LIST = 6001113

Global Const ID_PENJUALAN_MAINMENU_TABLE_CATAGORI = 600112
Global Const ID_PENJUALAN_MAINMENU_TABLE_CATAGORI_ADD = 6001121
Global Const ID_PENJUALAN_MAINMENU_TABLE_CATAGORI_CHANGE = 6001122
Global Const ID_PENJUALAN_MAINMENU_TABLE_CATAGORI_LIST = 6001123

Global Const ID_PENJUALAN_MAINMENU_TABLE_BARANGJADI = 600113
Global Const ID_PENJUALAN_MAINMENU_TABLE_BARANGJADI_MANAGE = 6001131
Global Const ID_PENJUALAN_MAINMENU_TABLE_BARANGJADI_LIST = 6001132

Global Const ID_PENJUALAN_MAINMENU_TABLE_GUDANG = 600114
Global Const ID_PENJUALAN_MAINMENU_TABLE_GUDANG_ADD = 6001141
Global Const ID_PENJUALAN_MAINMENU_TABLE_GUDANG_CHANGE = 6001142
Global Const ID_PENJUALAN_MAINMENU_TABLE_GUDANG_LIST = 6001143

Global Const ID_PENJUALAN_MAINMENU_TABLE_AREA = 600115
Global Const ID_PENJUALAN_MAINMENU_TABLE_AREA_ADD = 6001151
Global Const ID_PENJUALAN_MAINMENU_TABLE_AREA_CHANGE = 6001152
Global Const ID_PENJUALAN_MAINMENU_TABLE_AREA_LIST = 6001153

Global Const ID_PENJUALAN_MAINMENU_TABLE_CUSTOMER = 600116
Global Const ID_PENJUALAN_MAINMENU_TABLE_CUSTOMER_ADD = 6001161
Global Const ID_PENJUALAN_MAINMENU_TABLE_CUSTOMER_CHANGE = 6001162
Global Const ID_PENJUALAN_MAINMENU_TABLE_CUSTOMER_LIST = 6001163

Global Const ID_PENJUALAN_MAINMENU_TABLE_SALES = 600117
Global Const ID_PENJUALAN_MAINMENU_TABLE_SALES_MANAGE = 6001171

Global Const ID_PENJUALAN_MAINMENU_MUTASI = 60012
Global Const ID_PENJUALAN_MAINMENU_MUTASI_ADD = 600121
Global Const ID_PENJUALAN_MAINMENU_MUTASI_MUT = 600150
Global Const ID_PENJUALAN_MAINMENU_MUTASI_MUT_OVERZAK = 6001501
Global Const ID_PENJUALAN_MAINMENU_MUTASI_MUT_MUTASILOT = 6001502
Global Const ID_PENJUALAN_MAINMENU_MUTASI_MUT_MUTPABRIK = 6001503
Global Const ID_PENJUALAN_MAINMENU_MUTASI_MUT_ADJSTOK = 6001504
Global Const ID_PENJUALAN_MAINMENU_MUTASI_CHANGE = 600122
Global Const ID_PENJUALAN_MAINMENU_MUTASI_LIST = 600123
Global Const ID_PENJUALAN_MAINMENU_MUTASI_WIP = 600128
Global Const ID_PENJUALAN_MAINMENU_MUTASI_GUDANG = 600129
Global Const ID_PENJUALAN_MAINMENU_MUTASI_FAILED = 600130
Global Const ID_PENJUALAN_MAINMENU_MUTASI_KARTUSTOK = 600131
Global Const ID_PENJUALAN_MAINMENU_MUTASI_PINDAHGUDANG = 600124
Global Const ID_PENJUALAN_MAINMENU_MUTASI_PINDAHGUDANG_ADD = 6001241
Global Const ID_PENJUALAN_MAINMENU_MUTASI_PINDAHGUDANG_CHANGE = 6001242
Global Const ID_PENJUALAN_MAINMENU_MUTASI_PINDAHGUDANG_PRINT = 6001243
Global Const ID_PENJUALAN_MAINMENU_MUTASI_PINDAHGUDANG_LOTPALET = 6001244
Global Const ID_PENJUALAN_MAINMENU_MUTASI_PINDAHGUDANG_SCANPALET = 6001245
Global Const ID_PENJUALAN_MAINMENU_MUTASI_PINDAHGUDANG_COMPAREHPP = 6001247
Global Const ID_PENJUALAN_MAINMENU_MUTASI_PINDAHGUDANG_TOWIP = 6001246
Global Const ID_PENJUALAN_MAINMENU_MUTASI_PRINTPRICE = 600125
Global Const ID_PENJUALAN_MAINMENU_MUTASI_LISTSTOK = 600126
Global Const ID_PENJUALAN_MAINMENU_MUTASI_PACKLIST = 600127
Global Const ID_PENJUALAN_MAINMENU_MUTASI_PACKLIST_ADD = 6001271
Global Const ID_PENJUALAN_MAINMENU_MUTASI_PACKLIST_LIST = 6001272
Global Const ID_PENJUALAN_MAINMENU_MUTASI_PACKLIST_CLOSE = 6001273

Global Const ID_PENJUALAN_MAINMENU_INVOICING = 60013
Global Const ID_PENJUALAN_MAINMENU_INVOICING_SO = 600131
Global Const ID_PENJUALAN_MAINMENU_INVOICING_SO_ADD = 6001311
Global Const ID_PENJUALAN_MAINMENU_INVOICING_SO_CHANGE = 6001312
Global Const ID_PENJUALAN_MAINMENU_INVOICING_SO_CANCEL = 6001313
Global Const ID_PENJUALAN_MAINMENU_INVOICING_SJ = 600132
Global Const ID_PENJUALAN_MAINMENU_INVOICING_SJ_ADD = 6001321
Global Const ID_PENJUALAN_MAINMENU_INVOICING_SJ_CHANGE = 6001322
Global Const ID_PENJUALAN_MAINMENU_INVOICING_SJ_PRINT = 6001323
Global Const ID_PENJUALAN_MAINMENU_INVOICING_SJ_ADDLOT = 6001324
Global Const ID_PENJUALAN_MAINMENU_INVOICING_FAKTURJUAL = 600133
Global Const ID_PENJUALAN_MAINMENU_INVOICING_FAKTURJUAL_ADD = 6001334
Global Const ID_PENJUALAN_MAINMENU_INVOICING_FAKTURJUAL_CHANGE = 6001335
Global Const ID_PENJUALAN_MAINMENU_INVOICING_FAKTURJUAL_PRINT = 6001336
Global Const ID_PENJUALAN_MAINMENU_INVOICING_FAKTURJUAL_PREVIEW = 6001337

Global Const ID_PENJUALAN_MAINMENU_INVOICING_FAKTURPAJAK = 600134
Global Const ID_PENJUALAN_MAINMENU_INVOICING_FAKTURPAJAK_DEFINE = 6001341
Global Const ID_PENJUALAN_MAINMENU_INVOICING_FAKTURPAJAK_BROWSE = 6001342

Global Const ID_PENJUALAN_MAINMENU_INVOICING_SJSBY = 600135
Global Const ID_PENJUALAN_MAINMENU_INVOICING_SJSBY_ADD = 6001351
Global Const ID_PENJUALAN_MAINMENU_INVOICING_SJSBY_LIST = 6001352

Global Const ID_PENJUALAN_MAINMENU_INVOICING_INQUERYSO = 600136
Global Const ID_PENJUALAN_MAINMENU_INVOICING_LAPSO = 600137

Global Const ID_PENJUALAN_MAINMENU_INVOICING_LAPSJ = 600138
Global Const ID_PENJUALAN_MAINMENU_INVOICING_LAPSJ_DAFTAR = 6001381
Global Const ID_PENJUALAN_MAINMENU_INVOICING_LAPSJ_LAPORAN = 6001382
Global Const ID_PENJUALAN_MAINMENU_INVOICING_LAPSJ_DAFTARGD = 6001383
Global Const ID_PENJUALAN_MAINMENU_INVOICING_LAPSJ_BYFAKTUR = 6001384
Global Const ID_PENJUALAN_MAINMENU_INVOICING_LAPSJ_BYLOT = 6001385

Global Const ID_PENJUALAN_MAINMENU_INVOICING_LAPJUAL = 600139
Global Const ID_PENJUALAN_MAINMENU_INVOICING_LAPJUALDTL = 6001391
Global Const ID_PENJUALAN_MAINMENU_INVOICING_LAPKOMISI = 6001392
Global Const ID_PENJUALAN_MAINMENU_INVOICING_ANALISAJUAL = 6001393
Global Const ID_PENJUALAN_MAINMENU_INVOICING_MONTHLY = 6001394
Global Const ID_PENJUALAN_MAINMENU_INVOICING_BYKATEGORI = 6001395

Global Const ID_PENJUALAN_MAINMENU_UTILITY = 60014
Global Const ID_PENJUALAN_MAINMENU_UTILITY_OPTIONS = 600141
Global Const ID_PENJUALAN_MAINMENU_UTILITY_CANCELSO = 600142
Global Const ID_PENJUALAN_MAINMENU_UTILITY_CLOSESO = 600143

Global Const ID_PENJUALAN_MAINMENU_UTILITY_EXPORTSO = 600144
Global Const ID_PENJUALAN_MAINMENU_UTILITY_IMPORTSOPBRK = 600145

Global Const ID_PENJUALAN_MAINMENU_UTILITY_EXPORTSJ = 600146
Global Const ID_PENJUALAN_MAINMENU_UTILITY_IMPORTSJ = 600147

Global Const ID_PENJUALAN_MAINMENU_UTILITY_IMPORTINV = 600148
Global Const ID_PENJUALAN_MAINMENU_UTILITY_DELINV = 600149

'########################### SET PENJUALAN ##############################
Public PENJUALAN As RibbonTab
Public PENJUALAN_MAINMENU As RibbonGroup
Public PENJUALAN_MAINMENU_TABLES As CommandBarPopup

Public PENJUALAN_MAINMENU_TABLES_SATUAN As CommandBarPopup
Public PENJUALAN_MAINMENU_TABLES_SATUAN_ADD As CommandBarButton
Public PENJUALAN_MAINMENU_TABLES_SATUAN_CHANGE As CommandBarButton
Public PENJUALAN_MAINMENU_TABLES_SATUAN_LIST As CommandBarButton

Public PENJUALAN_MAINMENU_TABLES_CATAGORI As CommandBarPopup
Public PENJUALAN_MAINMENU_TABLES_CATAGORI_ADD As CommandBarButton
Public PENJUALAN_MAINMENU_TABLES_CATAGORI_CHANGE As CommandBarButton
Public PENJUALAN_MAINMENU_TABLES_CATAGORI_LIST As CommandBarButton

Public PENJUALAN_MAINMENU_TABLES_BARANGJADI As CommandBarPopup
Public PENJUALAN_MAINMENU_TABLES_BARANGJADI_MANAGE As CommandBarButton
Public PENJUALAN_MAINMENU_TABLES_BARANGJADI_LIST As CommandBarButton

Public PENJUALAN_MAINMENU_TABLES_GUDANG As CommandBarPopup
Public PENJUALAN_MAINMENU_TABLES_GUDANG_ADD As CommandBarButton
Public PENJUALAN_MAINMENU_TABLES_GUDANG_CHANGE As CommandBarButton
Public PENJUALAN_MAINMENU_TABLES_GUDANG_LIST As CommandBarButton

Public PENJUALAN_MAINMENU_TABLES_AREA As CommandBarPopup
Public PENJUALAN_MAINMENU_TABLES_AREA_ADD As CommandBarButton
Public PENJUALAN_MAINMENU_TABLES_AREA_CHANGE As CommandBarButton
Public PENJUALAN_MAINMENU_TABLES_AREA_LIST As CommandBarButton

Public PENJUALAN_MAINMENU_TABLES_CUSTOMER As CommandBarPopup
Public PENJUALAN_MAINMENU_TABLES_CUSTOMER_ADD As CommandBarButton
Public PENJUALAN_MAINMENU_TABLES_CUSTOMER_CHANGE As CommandBarButton
Public PENJUALAN_MAINMENU_TABLES_CUSTOMER_LIST As CommandBarButton

Public PENJUALAN_MAINMENU_TABLES_SALES As CommandBarPopup
Public PENJUALAN_MAINMENU_TABLES_SALES_MANAGE As CommandBarButton

Public PENJUALAN_MAINMENU_MUTASI As CommandBarPopup
Public PENJUALAN_MAINMENU_MUTASI_ADD As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_CHANGE As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_MUT As CommandBarPopup
Public PENJUALAN_MAINMENU_MUTASI_MUT_OVERZAK As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_MUT_MUTASILOT As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_MUT_MUTPABRIK As CommandBarButton
'Public PENJUALAN_MAINMENU_MUTASI_MUT_ADJSTOK As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_LIST As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_GUDANG As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_FAILED As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_WIP As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_KARTUSTOK As CommandBarButton
'Public PENJUALAN_MAINMENU_MUTASI_PINDAHGUDANG As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_PINDAHGUDANG_ADD As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_PINDAHGUDANG_CHANGE As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_PINDAHGUDANG_PRINT As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_PINDAHGUDANG_LOTPALET As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_PINDAHGUDANG_SCANPALET As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_PINDAHGUDANG_COMPAREHPP As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_PINDAHGUDANG_TOWIP As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_PRINTPRICE As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_LISTSTOK As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_PACKLIST As CommandBarPopup
Public PENJUALAN_MAINMENU_MUTASI_PACKLIST_ADD As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_PACKLIST_LIST As CommandBarButton
Public PENJUALAN_MAINMENU_MUTASI_PACKLIST_CLOSE As CommandBarButton

Public PENJUALAN_MAINMENU_INVOICING As CommandBarPopup
Public PENJUALAN_MAINMENU_INVOICING_SO As CommandBarPopup
Public PENJUALAN_MAINMENU_INVOICING_SO_ADD As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_SO_CHANGE As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_SO_CANCEL As CommandBarButton

Public PENJUALAN_MAINMENU_INVOICING_SJ As CommandBarPopup
Public PENJUALAN_MAINMENU_INVOICING_SJ_ADD As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_SJ_CHANGE As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_SJ_PRINT As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_SJ_ADDLOT As CommandBarButton

Public PENJUALAN_MAINMENU_INVOICING_FAKTURJUAL As CommandBarPopup
Public PENJUALAN_MAINMENU_INVOICING_FAKTURJUAL_ADD As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_FAKTURJUAL_CHANGE As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_FAKTURJUAL_PRINT As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_FAKTURJUAL_PREVIEW As CommandBarButton

Public PENJUALAN_MAINMENU_INVOICING_FAKTURPAJAK As CommandBarPopup
Public PENJUALAN_MAINMENU_INVOICING_FAKTURPAJAK_DEFINE As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_FAKTURPAJAK_BROWSE As CommandBarButton

Public PENJUALAN_MAINMENU_INVOICING_SJSBY As CommandBarPopup
Public PENJUALAN_MAINMENU_INVOICING_SJSBY_ADD As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_SJSBY_LIST As CommandBarButton

Public PENJUALAN_MAINMENU_INVOICING_INQUERYSO As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_LAPSO As CommandBarButton

Public PENJUALAN_MAINMENU_INVOICING_LAPSJ As CommandBarPopup
Public PENJUALAN_MAINMENU_INVOICING_LAPSJ_DAFTAR As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_LAPSJ_DAFTARGD As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_LAPSJ_LAPORAN As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_LAPSJ_BYFAKTUR As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_LAPSJ_BYLOT As CommandBarButton

Public PENJUALAN_MAINMENU_INVOICING_LAPJUAL As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_LAPJUALDTL As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_KOMISI As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_ANALISAJUAL As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_MONTHLY As CommandBarButton
Public PENJUALAN_MAINMENU_INVOICING_BYKATEGORI As CommandBarButton

Public PENJUALAN_MAINMENU_UTILITY As CommandBarPopup
Public PENJUALAN_MAINMENU_UTILITY_OPTIONS As CommandBarButton
Public PENJUALAN_MAINMENU_UTILITY_CANCELSO As CommandBarButton
Public PENJUALAN_MAINMENU_UTILITY_CLOSESO As CommandBarButton

Public PENJUALAN_MAINMENU_UTILITY_EXPORTSO As CommandBarButton
Public PENJUALAN_MAINMENU_UTILITY_IMPORTSO As CommandBarButton

Public PENJUALAN_MAINMENU_UTILITY_EXPORTSJ As CommandBarButton
Public PENJUALAN_MAINMENU_UTILITY_IMPORTSJ As CommandBarButton

Public PENJUALAN_MAINMENU_UTILITY_IMPORTINV As CommandBarButton

Public PENJUALAN_MAINMENU_UTILITY_DELINV As CommandBarButton

'############################# SET GUDANG ################################
Public GUDANG As RibbonTab
Public GUDANG_MAINMENU As RibbonGroup

'############################ ABOUT US ###################################
Global Const ID_ABOUT = 9000
Global Const ID_ABOUT_HOME = 90001
Global Const ID_ABOUT_HOME_ABOUTUS = 900011
Global Const ID_ABOUT_HOME_HELP = 900012
Global Const ID_ABOUT_HOME_HELP_HELP = 9000121
Global Const ID_ABOUT_HOME_HELP_HELP_NP = 90001211
Global Const ID_ABOUT_HOME_HELP_HELP_NPEDIT = 90001212
Global Const ID_ABOUT_HOME_HELP_HELP_NPPRINT = 90001213
Global Const ID_ABOUT_HOME_HELP_HELP_TS = 90001214
Global Const ID_ABOUT_HOME_HELP_HELP_CETAKITG = 90001215
Global Const ID_ABOUT_HOME_HELP_HELP_CETAKREKAP = 90001216
Global Const ID_ABOUT_HOME_HELP_HELP_LEMBUR = 90001217
Global Const ID_ABOUT_HOME_HELP_HELP_KAS = 90001218
Global Const ID_ABOUT_HOME_HELP_FORM = 9000122
Global Const ID_ABOUT_HOME_CHECKUPDATE = 900013

Public ABOUT As RibbonTab
Public ABOUT_HOME As RibbonGroup
Public ABOUT_HOME_ABOUTUS As CommandBarButton
Public ABOUT_HOME_HELP As CommandBarPopup
Public ABOUT_HOME_HELP_HELP As CommandBarPopup
Public ABOUT_HOME_HELP_HELP_NP As CommandBarButton
Public ABOUT_HOME_HELP_HELP_NPEDIT As CommandBarButton
Public ABOUT_HOME_HELP_HELP_NPPRINT As CommandBarButton
Public ABOUT_HOME_HELP_HELP_TS As CommandBarButton
Public ABOUT_HOME_HELP_HELP_CETAKITG As CommandBarButton
Public ABOUT_HOME_HELP_HELP_CETAKREKAP As CommandBarButton
Public ABOUT_HOME_HELP_HELP_LEMBUR As CommandBarButton
Public ABOUT_HOME_HELP_HELP_KAS As CommandBarButton
Public ABOUT_HOME_HELP_FORM As CommandBarButton
Public ABOUT_HOME_CHECKUPDATE As CommandBarButton

'############################### OPTION ID ############
Public Const ID_OPTIONS_STYLEBLUE = 7000
Public Const ID_OPTIONS_STYLEBLACK = 7001
Public Const ID_OPTIONS_STYLEAQUA = 7002
Public Const ID_OPTIONS_STYLESILVER = 7003
Public Const ID_OPTIONS_RTL = 7004
Public Const ID_OPTIONS_ANIMATION = 7005
Public Const ID_OPTIONS_STYLESYSTEM = 7006
Public Const ID_OPTIONS_STYLESCENIC = 7007
Public Const ID_OPTIONS_STYLEWHITE = 7008
